Revert "Fix warning: 'what' hides overloaded virtual function"
This reverts commit a0d379905c2e06bd00d97548b3ab03c1f566f420,
which causes an "undefined reference to `vtable for CGameException'"
error on MinGW.